### ISSUE TITLE
[#1753] Dijkstra 

### ISSUE THREAD

**Issue by euije** [AlgoLive/AlgoLive_Session#2]
https://github.com/AlgoLive/AlgoLive_Session/blob/e3158f20515ad3aba7b2208a9d5b5609da6bfd0e/Example/1753.java#L26

해당 큰 수 모든 케이스를 충분이 커버 가능한가요?

**Comment by win-luck** [comment]
저도 웹서핑해서 찾은거라 확답하긴 어려우나, 문제는 없습니다.
https://sangwoo0727.github.io/java/JAVA-4_constants/

**Comment by euije** [comment]
<img width="515" alt="스크린샷 2022-06-23 오후 3 21 08" src="https://user-images.githubusercontent.com/12531340/175229213-32c525e9-e381-470f-b87f-5d44a3172314.png">

아하 자바는 큰 수를 이런식으로 넣는 군요,

해당 숫자면 int 범위에서  오버플로우 없이 handle 가능하겠네요!
